### ISSUE TITLE
kanban board for capstone group javascript project

### ISSUE THREAD

**Issue by JakariaJishan** [elad237/TV-show-Api#22]
https://github.com/elad237/TV-show-Api/projects/2
A team of 2 people.

**Comment by leonardodiasb** [comment]
# Status: ✔️ Project Approved ✔️ 

Hi @elad237,

Everything is looking great! Please, merge start the project :shipit:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
